image: node:14.15.5-alpine3.12

stages:
  - test

tests_stage:
  stage: test
  script:
    - apk update
    - apk add libgbm-dev libgtk-3-0 libnss3 libx11-xcb1 libasound2
    # Full list of potentially packages necessary for puppeteer at: https://techoverflow.net/2018/06/05/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-cannot-open-shared-object-file-no-such-file-or-directory/
    - npm install 
    - npm test
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
