stages:
  - build
  - test

image: node

build_stage:
  stage: build
  script:
    - ls -l
    - npm install

tests_stage:
  stage: test
  script:
    - echo 'start NPM Test'
    - npm test
    - echo 'end NPM Test'
  artifacts:
    when: always
    reports:
      junit:
        - ls -l
        - junit.xml
