image: buildkite/puppeteer:latest

stages:
  - test

tests_stage:
  stage: test
  script:
    - npm install 
    - npm test    
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
