image: node

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build_stage:
  stage: build
  script:
    - ls -l
    - npm install
  artifacts:
    paths:
      - node_modules/

tests_stage:
  stage: test
  script:
    - echo 'start NPM Test'
    - npm install jest --save-dev
    - npm test
    - echo 'end NPM Test'
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
