image: node:14.15.5-alpine3.12

stages:
  - test

tests_stage:
  stage: test
  script:
    - apk update
    - apk add g++ make unzip chromium
    - npm install
    - npm test
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
