image: node

stages:
  - test

tests_stage:
  stage: test
  script:
    - apt update
    - apt install libnss3 -y
    - npm install 
    - npm test    
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
