stages:
  - build
  - test

image: node

build_stage:
  stage: build
  script:
    - ls
    - npm install
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

tests_stage:
  stage: test
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
