image: node:14.15.5-buster-slim

stages:
  - test

tests_stage:
  stage: test
  script:
    - npm install 
    - apt update
    - apt install -y libgbm-dev
    - npm test    
    - apt install -y libasound2
    - apk install -y libatk1.0-0
    - apk install -y libc6
    - apk install -y libcairo2
    - apk install -y libcups2
    - apk install -y libdbus-1-3
    - apk install -y libexpat1
    - apk install -y libfontconfig1
    - apk install -y libgcc1
    - apk install -y libgconf-2-4
    - apk install -y libgdk-pixbuf2.0-0
    - apk install -y libglib2.0-0
    - apk install -y libgtk-3-0
    - apk install -y libnspr4
    - apk install -y libpango-1.0-0
    - apk install -y libpangocairo-1.0-0
    - apk install -y libstdc++6
    - apk install -y libx11-6
    - apk install -y libx11-xcb1
    - apk install -y libxcb1
    - apk install -y libxcomposite1
    - apk install -y libxcursor1
    - apk install -y libxdamage1
    - apk install -y libxext6
    - apk install -y libxfixes3
    - apk install -y libxi6
    - apk install -y libxrandr2
    - apk install -y libxrender1
    - apk install -y libxss1
    - apk install -y libxtst6
    - apk install -y libappindicator1
    - apk install -y libnss3
    - npm install 
    - npm test    
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
