image: node:14.15.5-buster-slim

stages:
  - test

tests_stage:
  stage: test
  script:
    - apk update
    - apk add libnss3 libatk-b
    - npm install 
    - npm test    
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
