image: node:14.15.5-buster-slim

stages:
  - test

tests_stage:
  stage: test
  script:
    - apt update
    - apt install libnss3 libgobject-2.0.so.0 -y
    - npm install 
    - npm test    
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
