image: node:14.15.5-alpine3.12

stages:
  - test

tests_stage:
  stage: test
  script:
    - apk update
    - apk add --update --no-cache chromium@3.10=~73.0.3683.103 \
      nss@3.10 \
      freetype@3.10 \
      harfbuzz@3.10 \
      ttf-freefont@3.10 \
      curl \
      bash \
    - npm install 
    - npm test
  artifacts:
    when: always
    reports:
      junit:        
        - junit.xml
