stages:
  - run-tests

image: node

tests_stage:
  stage: run-tests
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  only:
    refs:
      - main
